# Generated by Django 4.2.6 on 2023-12-14 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0007_historybarangmasuk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historybarangmasuk',
            name='jumlah',
        ),
        migrations.AlterField(
            model_name='historybarangmasuk',
            name='karyawan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sparepart.karyawan'),
        ),
        migrations.AlterField(
            model_name='historybarangmasuk',
            name='sparepart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sparepart.sparepart'),
        ),
    ]
