# Generated by Django 4.2.6 on 2023-12-14 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0008_remove_historybarangmasuk_jumlah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historybarangmasuk',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
