# Generated by Django 4.2.6 on 2023-12-14 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0011_alter_historybarangmasuk_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='historybarangmasuk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='historybarangmasuk',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
