# Generated by Django 4.2.7 on 2023-12-16 10:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0012_historybarangmasuk_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historybarangmasuk',
            name='karyawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sparepart.karyawan'),
        ),
        migrations.AlterField(
            model_name='historybarangmasuk',
            name='sparepart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sparepart.sparepart'),
        ),
        migrations.CreateModel(
            name='HistoryBarangKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('jumlah', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sparepart.karyawan')),
                ('sparepart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sparepart.sparepart')),
            ],
        ),
    ]
